/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.splashscreen;

import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialDeepOceanIJTheme;
import java.util.Random;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;

/**
 *
 * @author Carlos de los Dolores Macías
 */
public class Loading extends javax.swing.JFrame {

    /**
     * Creates new form Loading
     */
    public Loading() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        bar = new javax.swing.JProgressBar();
        prep = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        imagenFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        fondo.setBackground(new java.awt.Color(153, 153, 255));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bar.setForeground(new java.awt.Color(102, 102, 255));
        bar.setBorderPainted(false);
        fondo.add(bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 388, 20));

        prep.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        prep.setForeground(new java.awt.Color(102, 153, 255));
        prep.setText("Cargando...");
        fondo.add(prep, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 153, 255));
        jLabel2.setText("Espere un momento");
        fondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        imagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rose.jpg"))); // NOI18N
        fondo.add(imagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    // Configurar el tema Flat Material Deep Ocean IJ
    FlatMaterialDeepOceanIJTheme.setup();

    // Crear una instancia de Loading (ventana de carga)
    Loading lc = new Loading();

    // Mostrar la ventana de carga en el hilo de eventos de Swing (EDT)
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            lc.setVisible(true);
        }
    });

    try {
        // Simular el progreso (del 0 al 100)
        for (int i = 0; i <= 100; i++) {
            // Simular una pausa para mostrar el progreso
            Thread.sleep(50);

            final int progress = i;

            // Actualizar la barra de progreso y el texto de preparación en el hilo EDT
            SwingUtilities.invokeLater(() -> {
                lc.bar.setValue(progress);

                // Actualizar el texto de preparación según el progreso
                if (progress <= 20) {
                    lc.prep.setText("Preparando el sistema..." + progress + "%");
                } else if (progress <= 50) {
                    lc.prep.setText("Preparando recursos..." + progress + "%");
                } else if (progress <= 90) {
                    lc.prep.setText("Preparando interfaz..." + progress + "%");
                } else if (progress >= 100) {
                    lc.prep.setText("Listo");
                }
            });
        }
    } catch (Exception e) {
        // Manejar excepciones (en caso de interrupciones durante el progreso)
        System.out.println(e);
    }

    // Crear una instancia de la pantalla principal
    HomeScreen hm = new HomeScreen();

    // Ocultar la ventana de carga y mostrar la pantalla principal
    lc.setVisible(false);
    hm.setVisible(true); //Se muestra la HomeScreen

    // Cerrar la ventana de carga
    lc.dispose();
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar bar;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel imagenFondo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel prep;
    // End of variables declaration//GEN-END:variables
}
